name: Scrape Lpbcol website

on:
  workflow_dispatch:
  repository_dispatch:
    types: -webhook

jobs:
  scrape:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GI_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: pnpm/action-setup@v2
        with:
          version: 7.23.0
          run_install: true
      - run: |
          npm run scrape:final
          git config user.name lpbcol-bot
          git diff --quiet && git diff --staged --quiet || git commit -am "[🤖 bot] Update lpbcol database"
          git push origin main
